Repository AntonRufus/test-repo-react-app-resume, pull requests merged in 2021-02, with the labels that each got.

#3 Hello_Andrew.txt pull request
  src/Hello_Anrew.txt
Labels: bug

#15 test15
  src/test15NEWbla.txt
Labels: documentation, for Andrew

#26 footer init
  src/footer/footer.html
Labels: wontfix
